name: Build KTX Framework for macOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1.6.0
      with:
        xcode-version: '15.1'

    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Create build directory
      run: |
        mkdir -p build
        mkdir -p build/logs
      
    - name: Generate Xcode project
      run: cmake -G Xcode -B build/catalyst \
        -D CMAKE_SYSTEM_NAME=Darwin \
        -D CMAKE_OSX_ARCHITECTURES=arm64 \
        -D CMAKE_OSX_DEPLOYMENT_TARGET=13.0 \
        -D CMAKE_OSX_SYSROOT=$(xcrun --sdk macosx --show-sdk-path) \
        -D CMAKE_CXX_FLAGS="-target arm64-apple-ios14.0-macabi" \
        -D CMAKE_C_FLAGS="-target arm64-apple-ios14.0-macabi" \
        -D CMAKE_SHARED_LINKER_FLAGS="-target arm64-apple-ios14.0-macabi -isysroot $(xcrun --sdk macosx --show-sdk-path)" \
        -D CMAKE_EXE_LINKER_FLAGS="-target arm64-apple-ios14.0-macabi -isysroot $(xcrun --sdk macosx --show-sdk-path)"

    - name: Build for osx
      run: cmake --build build/catalyst --config Release -- -sdk macosx EXCLUDED_ARCHS=x86_64

    - name: Create XCFramework
      run: |
        xcodebuild -create-xcframework \
          -framework build/catalyst/Release-macosx/ktx.framework \
          -output ktx.xcframework
    - uses: actions/upload-artifact@v4
      with:
        name: ktx.xcframework
        path: ktx.xcframework

    - uses: actions/upload-artifact@v4
      with:
          name: build_logs
          path: build/logs/
